## Problem 1
**Matrix Product is Calculated Manually**

$
A = \begin{bmatrix}
-1 & 2 & 3\\
4 & -5 & 6\\
7 & 8 & -9
\end{bmatrix}
$  
<br>

$
B = \begin{bmatrix}
0 & 2 & 1\\
0 & 2 & -8\\
2 & 9 & -1
\end{bmatrix}
$  
<br>

$
A \times B = \begin{bmatrix}
-1 & 2 & 3\\
4 & -5 & 6\\
7 & 8 & -9
\end{bmatrix} \times \begin{bmatrix}
0 & 2 & 1\\
0 & 2 & -8\\
2 & 9 & -1
\end{bmatrix}
$  
<br>
Matrix multiplication is done by calculating the dot product of each row of matrix A with each column of matrix B
<br>
i.e $A \cdot B[i,j] = A[i,0] \cdot B[0,j] + A[i,1] \cdot B[1,j] + A[i,2] \cdot B[2,j]$  
<br>

$
A \times B = \begin{bmatrix}
((−1)\cdot0+2\cdot0+3\cdot2) & ((-1)\cdot2+2\cdot2+3\cdot9) & ((-1)\cdot1+2\cdot(-8)+3\cdot(-1))\\
(4\cdot0+(-5)\cdot0+6\cdot2) & (4\cdot2+(-5)\cdot2+6\cdot9) & (4\cdot1+(-5)\cdot(-8)+6\cdot(-1))\\
(7\cdot0+8\cdot0+(-9)\cdot2) & (7\cdot2+8\cdot2+(-9)\cdot9) & (7\cdot1+8\cdot(-8)+(-9)\cdot(-1))
\end{bmatrix}
$  
<br>

$
A \times B = \begin{bmatrix}
6 & 29 & -20\\
12 & 52 & 38\\
-18 & -51 & -48
\end{bmatrix}
$  
<br>
This is the result of multiplying matrices A and B by hand. 

## Problem 2
**Calculation by Numpy Function**

In [1]:
import numpy as np

In [2]:
A = np.array([[-1, 2 ,3], [4, -5, 6], [7, 8, -9]])
A

array([[-1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

In [3]:
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
B

array([[ 0,  2,  1],
       [ 0,  2, -8],
       [ 2,  9, -1]])

In [4]:
np.matmul(A, B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [5]:
np.dot(A, B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [ ]:
A@B

## Problem 3
**Implementation of Calculation of a Certain Element**