## Problem 1
**Matrix product is calculated manually**

$
A = \begin{bmatrix}
-1 & 2 & 3\\
4 & -5 & 6\\
7 & 8 & -9
\end{bmatrix}
$  
<br>

$
B = \begin{bmatrix}
0 & 2 & 1\\
0 & 2 & -8\\
2 & 9 & -1
\end{bmatrix}
$  
<br>

To find the matrix product of A and B, denoted as AB, you need to perform the dot product of each row of A with each column of B. Let's denote the elements of the resulting matrix as C. The element in the ith row and jth column of C (denoted as $C[i, j]$) is calculated as follows:  
<br>
$C[i,j] = A[i,0] \cdot B[0,j] + A[i,1] \cdot B[1,j] + A[i,2] \cdot B[2,j]$  
<br>

$
C = \begin{bmatrix}
-1 & 2 & 3\\
4 & -5 & 6\\
7 & 8 & -9
\end{bmatrix} \times \begin{bmatrix}
0 & 2 & 1\\
0 & 2 & -8\\
2 & 9 & -1
\end{bmatrix}
$  
<br>

$
C = \begin{bmatrix}
((-1)\cdot0+2\cdot0+3\cdot2) & ((-1)\cdot2+2\cdot2+3\cdot9) & ((-1)\cdot1+2\cdot(-8)+3\cdot(-1))\\
(4\cdot0+(-5)\cdot0+6\cdot2) & (4\cdot2+(-5)\cdot2+6\cdot9) & (4\cdot1+(-5)\cdot(-8)+6\cdot(-1)\\
(7\cdot0+8\cdot0+(-9)\cdot2) & (7\cdot2+8\cdot2+(-9)\cdot9) & (7\cdot1+8\cdot(-8)+(-9)\cdot(-1)
\end{bmatrix}
$  
<br>

$
C = \begin{bmatrix}
6 & 29 & -20\\
12 & 52 & 38\\
-18 & -51 & -48
\end{bmatrix}
$  
<br>

## Problem 2
**Calculation by Numpy Function**

In [1]:
import numpy as np

In [2]:
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
A

array([[-1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

In [3]:
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
B

array([[ 0,  2,  1],
       [ 0,  2, -8],
       [ 2,  9, -1]])

In [4]:
np.matmul(A, B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [5]:
np.dot(A, B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [6]:
A@B

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## Problem 3
**Implementation of calculation of a certain element**

Calculation for element $C_{ij}$ where i=0, j=0

In [7]:
i=0
j=0
c = np.sum(A[i, :]*B[:, j].T)
c

6

## Problem 4
**Creating a function that performs matrix multiplication**

In [8]:
def compute_matrix_multiplication(array_A, array_B):
    # Retrieve number of rows in array_A and number of columns in array_B
    a_rows = array_A.shape[0]
    b_columns = array_B.shape[1]
    
    # List to store the values
    product_list = []
    
    for i in range(a_rows):
        for j in range(b_columns):
            value = np.sum(array_A[i,:]*array_B[:,j].T)
            product_list.append(value)
    
    array_c = np.array(product_list).reshape(a_rows, b_columns)
    return array_c

compute_matrix_multiplication(A, B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## Problem 5
**Judge the input whose calculation is not defined**

In [9]:
D = np.array([[-1, 2, 3], [4, -5, 6]])
E = np.array([[-9, 8, 7], [6, -5, 4]])
compute_matrix_multiplication(D, E)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [11]:
def compute_matrix_multiplication(array_A, array_B):
    # Retrieve number of rows in array_A and number of columns in array_B
    a_rows = array_A.shape[0]
    b_columns = array_B.shape[1]
    
    # Make sure a_rows equals b_columns
    if a_rows!=b_columns:
        return "The number of rows in the first matrix should equal the number of columns in the second matrix"
    
    # List to store the values
    product_list = []
    
    for i in range(a_rows):
        for j in range(b_columns):
            value = np.sum(array_A[i,:]*array_B[:,j].T)
            product_list.append(value)
    
    array_c = np.array(product_list).reshape(a_rows, b_columns)
    return array_c

In [12]:
compute_matrix_multiplication(D, E)

'The number of rows in the first matrix should equal the number of columns in the second matrix'

## Problem 6
**Transposition**

In [13]:
E_transpose = E.T
compute_matrix_multiplication(D, E_transpose)

array([[ 46,  -4],
       [-34,  73]])